version: '3.7'

services:
  osv-scanner-tool:
    container_name: osv-scanner-tool
    image: owenwilson/osv-scanner-tool-security:latest
    ports:
      - 9898:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      osv-scanner-net:

networks:
  osv-scanner-net:
